import {Vazirmatn} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import {ThemeProvider} from "next-themes";
import {SessionProvider} from "next-auth/react";

const vazirmatn = Vazirmatn({
    variable: "--font-vazirmatn",
    subsets: ["latin", "arabic"],
});

export const metadata = {
    title: "مدیریت مالی شخصی",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" dir="rtl" suppressHydrationWarning>
            <body className={`${vazirmatn.variable} antialiased bg-gray-200 dark:bg-slate-800`}>
                <SessionProvider>
                    <ThemeProvider attribute="data-theme">
                        <Navbar/>
                        <div className="max-w-7xl mx-auto">{children}</div>
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
